/* tslint:disable */
/* eslint-disable */
/**
 * ProductPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Recipe,
    RecipeFromJSON,
    RecipeToJSON,
} from '../models';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Returns a list of recipes.
     */
    async recipesGetRaw(): Promise<runtime.ApiResponse<Array<Recipe>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/recipes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RecipeFromJSON));
    }

    /**
     * Returns a list of recipes.
     */
    async recipesGet(): Promise<Array<Recipe>> {
        const response = await this.recipesGetRaw();
        return await response.value();
    }

}
