openapi: 3.0.0
info:
  title: ProductPlanner API
  version: 0.1.0
servers:
  - url: http://localhost:3000
paths:
  /recipes:
    get:
      summary: Returns a list of recipes.
      responses:
        '200':
          description: A JSON array of user recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'

components:
  schemas:
    Ingredient:
      type: object
      properties:
        title:
          type: string
        unit:
          type: string
        value:
          type: integer
      required:
        - title
        - unit
        - value
    Recipe:
      type: object
      properties:
        id:
          type: integer
        ingridients:
          items:
            $ref: '#/components/schemas/Ingredient'
          type: array
        title:
          type: string
        image:
          type: string
      required:
        - id
        - title
